[project]
name = "cs50ai"
version = "0.1.0"
description = "https://cs50.harvard.edu/ai/"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "check50>=3.4.0",
    "submit50>=3.2.1",
]
